title: Martyn Egan # your name (or website title) here
logo: "/images/87206678.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Teaching Fellow in Applied Social Data Science at the Dept. of Political Science, Trinity College, Dublin 
  <br><br>
  Researcher in Social Reproduction and Inequality, using Geometric Data Analysis, Multiple Correspondence Analysis and Principal Components Analysis 
  <br><br>
  <a href="https://orcid.org/0000-0001-8070-5964">View My ORCID Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
