title: Martyn Egan 
logo: "/images/logo.png?raw=true" 
description: > 
  Assistant Professor in Political Science and Data Science, Trinity College, Dublin
  <br><br>
  Researcher in Social Reproduction and Inequality
  <br><br>
  <a href="https://orcid.org/0000-0001-8070-5964">View My ORCID Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-M78L595HQ1
