title: Martyn Egan 
logo: "/images/logo.png?raw=true" 
description: > 
  Assistant Professor in Political Science and Data Science, Trinity College, Dublin
  <br><br>
  Researcher in Social Reproduction and Inequality
  <br><br>
  View My <a href="https://orcid.org/0000-0001-8070-5964">ORCID Profile</a> 
  |
  <a href="https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=6582768">SSRN</a>
  
theme: jekyll-theme-minimal
